#pragma once
#include "Policy.hpp"
#include <RE/Skyrim.h>
#include <REL/Relocation.h>
#include <SKSE/SKSE.h>
#include <Windows.h>
#include <chrono>
#include <d3d11.h>
#include <dxgi.h>
#include <filesystem>
#include <mutex>
#include <spdlog/sinks/basic_file_sink.h>
#include <wrl/client.h>
